package xyz.baz9k.UHCGame.util;

import net.md_5.bungee.api.ChatColor;
import net.md_5.bungee.api.chat.BaseComponent;
import net.md_5.bungee.api.chat.ClickEvent;
import net.md_5.bungee.api.chat.ComponentBuilder;
import net.md_5.bungee.api.chat.HoverEvent;
import net.md_5.bungee.api.chat.ComponentBuilder.FormatRetention;

import java.awt.*;

public class ColoredStringBuilder {

    private final ComponentBuilder cb = new ComponentBuilder();


    public static ColoredStringBuilder of(String s, ChatColor c) {
        return new ColoredStringBuilder().append(s, c);
    }
    public static ColoredStringBuilder of(BaseComponent[] bc) {
        return new ColoredStringBuilder().append(bc);
    }

    /**
     * Coerce an object to string and append to builder.
     * @param o
     * @return
     */
    public ColoredStringBuilder append(Object o) {
        return append(String.valueOf(o));
    }

    /**
     * Append a piece of text directly to builder.
     * @param s
     * @return
     * @see #appendColored(String)
     */
    public ColoredStringBuilder append(String s) {
        cb.append(s, FormatRetention.NONE);
        return this;
    }

    /**
     * Append BaseComponents to builder.
     * @param bc
     * @return
     */
    public ColoredStringBuilder append(BaseComponent... bc) {
        cb.append(bc, FormatRetention.NONE);
        return this;
    }

    /**
     * Append a string with {@link Color} c to builder.
     * @param s
     * @param c
     * @return
     */
    public ColoredStringBuilder append(String s, Color c) {
        ChatColor cc = ChatColor.of(c);
        append(s, cc);
        return this;
    }

    /**
     * Append a string with {@link ChatColor} c to builder.
     * @param s
     * @param clr
     * @return
     */
    public ColoredStringBuilder append(String s, ChatColor c) {
        if (c.getColor() == null) throw new IllegalArgumentException("Argument clr is not a color.");

        cb.append(s, FormatRetention.NONE)
          .color(c);
        return this;
    }

    /**
     * Append a colored string (the kind generated by ChatColor + String concatenation) to builder.
     * @param s
     * @return
     */
    public ColoredStringBuilder appendColored(String s) {
        cb.appendLegacy(s);
        return this;
    }

    /**
     * Set most recently appended item's color
     * @param clr
     * @return
     */
    public ColoredStringBuilder color(ChatColor clr) {
        if (clr.getColor() == null) throw new IllegalArgumentException("Argument clr is not a color.");
        cb.color(clr);
        return this;
    }

    /**
     * Set most recently appended item's bold status
     * @param bold
     * @return
     */
    public ColoredStringBuilder bold(boolean bold) {
        cb.bold(bold);
        return this;
    }

    /**
     * Set most recently appended item's italic status
     * @param italic
     * @return
     */
    public ColoredStringBuilder italic(boolean italic) {
        cb.italic(italic);
        return this;
    }

    /**
     * Set most recently appended item's underlined status
     * @param underlined
     * @return
     */
    public ColoredStringBuilder underlined(boolean underlined) {
        cb.underlined(underlined);
        return this;
    }

    /**
     * Set most recently appended item's strikethrough status
     * @param strikethrough
     * @return
     */
    public ColoredStringBuilder strikethrough(boolean strikethrough) {
        cb.strikethrough(strikethrough);
        return this;
    }

    /**
     * Set most recently appended item's obfuscated status
     * @param obfuscated
     * @return
     */
    public ColoredStringBuilder obfuscated(boolean obfuscated) {
        cb.obfuscated(obfuscated);
        return this;
    }

    /**
     * Set most currently appended item's {@link ClickEvent}
     * @param event
     * @return
     */
    public ColoredStringBuilder event(ClickEvent event) {
        cb.event(event);
        return this;
    }
    
    /**
     * Set most currently appended item's {@link HoverEvent}
     * @param event
     * @return
     */
    public ColoredStringBuilder event(HoverEvent event) {
        cb.event(event);
        return this;
    }

    /**
     * Convert builder into an array of {@link BaseComponent}s.
     */
    public BaseComponent[] toComponents() {
        return cb.create();
    }

    /**
     * Convert builder to string.
     */
    public String toString() {
        return BaseComponent.toLegacyText(toComponents());
    }

}
